[project]
name = "opp"
version = "0.1.0"
description = ""
authors = [
    { name = "Pavel", email = "wtdtl07@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "pytest-cov (>=6.2.1,<7.0.0)",
    "python-telegram-bot (>=22.4,<23.0)",
    "openai (>=1.108.0,<2.0.0)",
    "transformers (>=4.56.1,<5.0.0)",
    "datasets (>=4.1.1,<5.0.0)",
    "matplotlib (>=3.10.6,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
